// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ArticleReferenceData {
  uint8 referenceType;
  string context;
}

library ArticleReference {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cms", name: "ArticleReference", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462636d73000000000000000000000041727469636c655265666572656e6365);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0001010101000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002005f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, string)
  Schema constant _valueSchema = Schema.wrap(0x0001010100c50000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "fromArticleId";
    keyNames[1] = "toArticleId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "referenceType";
    fieldNames[1] = "context";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get referenceType.
   */
  function getReferenceType(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (uint8 referenceType) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get referenceType.
   */
  function _getReferenceType(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (uint8 referenceType) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set referenceType.
   */
  function setReferenceType(bytes32 fromArticleId, bytes32 toArticleId, uint8 referenceType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((referenceType)), _fieldLayout);
  }

  /**
   * @notice Set referenceType.
   */
  function _setReferenceType(bytes32 fromArticleId, bytes32 toArticleId, uint8 referenceType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((referenceType)), _fieldLayout);
  }

  /**
   * @notice Get context.
   */
  function getContext(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (string memory context) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get context.
   */
  function _getContext(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (string memory context) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set context.
   */
  function setContext(bytes32 fromArticleId, bytes32 toArticleId, string memory context) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((context)));
  }

  /**
   * @notice Set context.
   */
  function _setContext(bytes32 fromArticleId, bytes32 toArticleId, string memory context) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((context)));
  }

  /**
   * @notice Get the length of context.
   */
  function lengthContext(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of context.
   */
  function _lengthContext(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of context.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemContext(
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of context.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemContext(
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to context.
   */
  function pushContext(bytes32 fromArticleId, bytes32 toArticleId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to context.
   */
  function _pushContext(bytes32 fromArticleId, bytes32 toArticleId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from context.
   */
  function popContext(bytes32 fromArticleId, bytes32 toArticleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from context.
   */
  function _popContext(bytes32 fromArticleId, bytes32 toArticleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of context at `_index`.
   */
  function updateContext(bytes32 fromArticleId, bytes32 toArticleId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of context at `_index`.
   */
  function _updateContext(bytes32 fromArticleId, bytes32 toArticleId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (ArticleReferenceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 fromArticleId, bytes32 toArticleId) internal view returns (ArticleReferenceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 fromArticleId, bytes32 toArticleId, uint8 referenceType, string memory context) internal {
    bytes memory _staticData = encodeStatic(referenceType);

    EncodedLengths _encodedLengths = encodeLengths(context);
    bytes memory _dynamicData = encodeDynamic(context);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 fromArticleId, bytes32 toArticleId, uint8 referenceType, string memory context) internal {
    bytes memory _staticData = encodeStatic(referenceType);

    EncodedLengths _encodedLengths = encodeLengths(context);
    bytes memory _dynamicData = encodeDynamic(context);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 fromArticleId, bytes32 toArticleId, ArticleReferenceData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.referenceType);

    EncodedLengths _encodedLengths = encodeLengths(_table.context);
    bytes memory _dynamicData = encodeDynamic(_table.context);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 fromArticleId, bytes32 toArticleId, ArticleReferenceData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.referenceType);

    EncodedLengths _encodedLengths = encodeLengths(_table.context);
    bytes memory _dynamicData = encodeDynamic(_table.context);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint8 referenceType) {
    referenceType = (uint8(Bytes.getBytes1(_blob, 0)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory context) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    context = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (ArticleReferenceData memory _table) {
    (_table.referenceType) = decodeStatic(_staticData);

    (_table.context) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 fromArticleId, bytes32 toArticleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 fromArticleId, bytes32 toArticleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint8 referenceType) internal pure returns (bytes memory) {
    return abi.encodePacked(referenceType);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory context) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(context).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory context) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((context)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint8 referenceType,
    string memory context
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(referenceType);

    EncodedLengths _encodedLengths = encodeLengths(context);
    bytes memory _dynamicData = encodeDynamic(context);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 fromArticleId, bytes32 toArticleId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = fromArticleId;
    _keyTuple[1] = toArticleId;

    return _keyTuple;
  }
}
