// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct BoostData {
  uint256 amount;
  address currency;
  uint8 boostType;
  uint64 endTime;
  uint256 totalImpressions;
  uint256 totalClicks;
  uint8 isActive;
}

library Boost {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cms", name: "Boost", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462636d730000000000000000000000426f6f73740000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x007e070020140108202001000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, address, uint64)
  Schema constant _keySchema = Schema.wrap(0x003c03005f610700000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, address, uint8, uint64, uint256, uint256, uint8)
  Schema constant _valueSchema = Schema.wrap(0x007e07001f6100071f1f00000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "articleId";
    keyNames[1] = "booster";
    keyNames[2] = "startTime";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](7);
    fieldNames[0] = "amount";
    fieldNames[1] = "currency";
    fieldNames[2] = "boostType";
    fieldNames[3] = "endTime";
    fieldNames[4] = "totalImpressions";
    fieldNames[5] = "totalClicks";
    fieldNames[6] = "isActive";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get amount.
   */
  function getAmount(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function _getAmount(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set amount.
   */
  function setAmount(bytes32 articleId, address booster, uint64 startTime, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _setAmount(bytes32 articleId, address booster, uint64 startTime, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Get currency.
   */
  function getCurrency(bytes32 articleId, address booster, uint64 startTime) internal view returns (address currency) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get currency.
   */
  function _getCurrency(bytes32 articleId, address booster, uint64 startTime) internal view returns (address currency) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set currency.
   */
  function setCurrency(bytes32 articleId, address booster, uint64 startTime, address currency) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currency)), _fieldLayout);
  }

  /**
   * @notice Set currency.
   */
  function _setCurrency(bytes32 articleId, address booster, uint64 startTime, address currency) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currency)), _fieldLayout);
  }

  /**
   * @notice Get boostType.
   */
  function getBoostType(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint8 boostType) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get boostType.
   */
  function _getBoostType(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint8 boostType) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set boostType.
   */
  function setBoostType(bytes32 articleId, address booster, uint64 startTime, uint8 boostType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((boostType)), _fieldLayout);
  }

  /**
   * @notice Set boostType.
   */
  function _setBoostType(bytes32 articleId, address booster, uint64 startTime, uint8 boostType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((boostType)), _fieldLayout);
  }

  /**
   * @notice Get endTime.
   */
  function getEndTime(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint64 endTime) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get endTime.
   */
  function _getEndTime(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint64 endTime) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set endTime.
   */
  function setEndTime(bytes32 articleId, address booster, uint64 startTime, uint64 endTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((endTime)), _fieldLayout);
  }

  /**
   * @notice Set endTime.
   */
  function _setEndTime(bytes32 articleId, address booster, uint64 startTime, uint64 endTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((endTime)), _fieldLayout);
  }

  /**
   * @notice Get totalImpressions.
   */
  function getTotalImpressions(
    bytes32 articleId,
    address booster,
    uint64 startTime
  ) internal view returns (uint256 totalImpressions) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalImpressions.
   */
  function _getTotalImpressions(
    bytes32 articleId,
    address booster,
    uint64 startTime
  ) internal view returns (uint256 totalImpressions) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalImpressions.
   */
  function setTotalImpressions(
    bytes32 articleId,
    address booster,
    uint64 startTime,
    uint256 totalImpressions
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((totalImpressions)), _fieldLayout);
  }

  /**
   * @notice Set totalImpressions.
   */
  function _setTotalImpressions(
    bytes32 articleId,
    address booster,
    uint64 startTime,
    uint256 totalImpressions
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((totalImpressions)), _fieldLayout);
  }

  /**
   * @notice Get totalClicks.
   */
  function getTotalClicks(
    bytes32 articleId,
    address booster,
    uint64 startTime
  ) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalClicks.
   */
  function _getTotalClicks(
    bytes32 articleId,
    address booster,
    uint64 startTime
  ) internal view returns (uint256 totalClicks) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalClicks.
   */
  function setTotalClicks(bytes32 articleId, address booster, uint64 startTime, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Set totalClicks.
   */
  function _setTotalClicks(bytes32 articleId, address booster, uint64 startTime, uint256 totalClicks) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((totalClicks)), _fieldLayout);
  }

  /**
   * @notice Get isActive.
   */
  function getIsActive(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get isActive.
   */
  function _getIsActive(bytes32 articleId, address booster, uint64 startTime) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set isActive.
   */
  function setIsActive(bytes32 articleId, address booster, uint64 startTime, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Set isActive.
   */
  function _setIsActive(bytes32 articleId, address booster, uint64 startTime, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 articleId, address booster, uint64 startTime) internal view returns (BoostData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 articleId, address booster, uint64 startTime) internal view returns (BoostData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 articleId,
    address booster,
    uint64 startTime,
    uint256 amount,
    address currency,
    uint8 boostType,
    uint64 endTime,
    uint256 totalImpressions,
    uint256 totalClicks,
    uint8 isActive
  ) internal {
    bytes memory _staticData = encodeStatic(
      amount,
      currency,
      boostType,
      endTime,
      totalImpressions,
      totalClicks,
      isActive
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 articleId,
    address booster,
    uint64 startTime,
    uint256 amount,
    address currency,
    uint8 boostType,
    uint64 endTime,
    uint256 totalImpressions,
    uint256 totalClicks,
    uint8 isActive
  ) internal {
    bytes memory _staticData = encodeStatic(
      amount,
      currency,
      boostType,
      endTime,
      totalImpressions,
      totalClicks,
      isActive
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 articleId, address booster, uint64 startTime, BoostData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.amount,
      _table.currency,
      _table.boostType,
      _table.endTime,
      _table.totalImpressions,
      _table.totalClicks,
      _table.isActive
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 articleId, address booster, uint64 startTime, BoostData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.amount,
      _table.currency,
      _table.boostType,
      _table.endTime,
      _table.totalImpressions,
      _table.totalClicks,
      _table.isActive
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 amount,
      address currency,
      uint8 boostType,
      uint64 endTime,
      uint256 totalImpressions,
      uint256 totalClicks,
      uint8 isActive
    )
  {
    amount = (uint256(Bytes.getBytes32(_blob, 0)));

    currency = (address(Bytes.getBytes20(_blob, 32)));

    boostType = (uint8(Bytes.getBytes1(_blob, 52)));

    endTime = (uint64(Bytes.getBytes8(_blob, 53)));

    totalImpressions = (uint256(Bytes.getBytes32(_blob, 61)));

    totalClicks = (uint256(Bytes.getBytes32(_blob, 93)));

    isActive = (uint8(Bytes.getBytes1(_blob, 125)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (BoostData memory _table) {
    (
      _table.amount,
      _table.currency,
      _table.boostType,
      _table.endTime,
      _table.totalImpressions,
      _table.totalClicks,
      _table.isActive
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 articleId, address booster, uint64 startTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 articleId, address booster, uint64 startTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 amount,
    address currency,
    uint8 boostType,
    uint64 endTime,
    uint256 totalImpressions,
    uint256 totalClicks,
    uint8 isActive
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(amount, currency, boostType, endTime, totalImpressions, totalClicks, isActive);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 amount,
    address currency,
    uint8 boostType,
    uint64 endTime,
    uint256 totalImpressions,
    uint256 totalClicks,
    uint8 isActive
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      amount,
      currency,
      boostType,
      endTime,
      totalImpressions,
      totalClicks,
      isActive
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    bytes32 articleId,
    address booster,
    uint64 startTime
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(booster)));
    _keyTuple[2] = bytes32(uint256(startTime));

    return _keyTuple;
  }
}
