// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TipData {
  uint256 amount;
  address currency;
  string message;
}

library Tip {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cms", name: "Tip", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462636d73000000000000000000000054697000000000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0034020120140000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, address, uint64)
  Schema constant _keySchema = Schema.wrap(0x003c03005f610700000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, address, string)
  Schema constant _valueSchema = Schema.wrap(0x003402011f61c500000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "articleId";
    keyNames[1] = "tipper";
    keyNames[2] = "timestamp";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "amount";
    fieldNames[1] = "currency";
    fieldNames[2] = "message";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get amount.
   */
  function getAmount(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function _getAmount(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (uint256 amount) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set amount.
   */
  function setAmount(bytes32 articleId, address tipper, uint64 timestamp, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _setAmount(bytes32 articleId, address tipper, uint64 timestamp, uint256 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Get currency.
   */
  function getCurrency(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (address currency) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get currency.
   */
  function _getCurrency(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (address currency) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set currency.
   */
  function setCurrency(bytes32 articleId, address tipper, uint64 timestamp, address currency) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currency)), _fieldLayout);
  }

  /**
   * @notice Set currency.
   */
  function _setCurrency(bytes32 articleId, address tipper, uint64 timestamp, address currency) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currency)), _fieldLayout);
  }

  /**
   * @notice Get message.
   */
  function getMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp
  ) internal view returns (string memory message) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get message.
   */
  function _getMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp
  ) internal view returns (string memory message) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set message.
   */
  function setMessage(bytes32 articleId, address tipper, uint64 timestamp, string memory message) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((message)));
  }

  /**
   * @notice Set message.
   */
  function _setMessage(bytes32 articleId, address tipper, uint64 timestamp, string memory message) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((message)));
  }

  /**
   * @notice Get the length of message.
   */
  function lengthMessage(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of message.
   */
  function _lengthMessage(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of message.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of message.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 _index
  ) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to message.
   */
  function pushMessage(bytes32 articleId, address tipper, uint64 timestamp, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to message.
   */
  function _pushMessage(bytes32 articleId, address tipper, uint64 timestamp, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from message.
   */
  function popMessage(bytes32 articleId, address tipper, uint64 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from message.
   */
  function _popMessage(bytes32 articleId, address tipper, uint64 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of message at `_index`.
   */
  function updateMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of message at `_index`.
   */
  function _updateMessage(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 _index,
    string memory _slice
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (TipData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 articleId, address tipper, uint64 timestamp) internal view returns (TipData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 amount,
    address currency,
    string memory message
  ) internal {
    bytes memory _staticData = encodeStatic(amount, currency);

    EncodedLengths _encodedLengths = encodeLengths(message);
    bytes memory _dynamicData = encodeDynamic(message);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 articleId,
    address tipper,
    uint64 timestamp,
    uint256 amount,
    address currency,
    string memory message
  ) internal {
    bytes memory _staticData = encodeStatic(amount, currency);

    EncodedLengths _encodedLengths = encodeLengths(message);
    bytes memory _dynamicData = encodeDynamic(message);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 articleId, address tipper, uint64 timestamp, TipData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.amount, _table.currency);

    EncodedLengths _encodedLengths = encodeLengths(_table.message);
    bytes memory _dynamicData = encodeDynamic(_table.message);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 articleId, address tipper, uint64 timestamp, TipData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.amount, _table.currency);

    EncodedLengths _encodedLengths = encodeLengths(_table.message);
    bytes memory _dynamicData = encodeDynamic(_table.message);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint256 amount, address currency) {
    amount = (uint256(Bytes.getBytes32(_blob, 0)));

    currency = (address(Bytes.getBytes20(_blob, 32)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory message) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    message = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (TipData memory _table) {
    (_table.amount, _table.currency) = decodeStatic(_staticData);

    (_table.message) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 articleId, address tipper, uint64 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 articleId, address tipper, uint64 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 amount, address currency) internal pure returns (bytes memory) {
    return abi.encodePacked(amount, currency);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory message) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(message).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory message) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((message)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 amount,
    address currency,
    string memory message
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(amount, currency);

    EncodedLengths _encodedLengths = encodeLengths(message);
    bytes memory _dynamicData = encodeDynamic(message);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    bytes32 articleId,
    address tipper,
    uint64 timestamp
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(tipper)));
    _keyTuple[2] = bytes32(uint256(timestamp));

    return _keyTuple;
  }
}
