// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TipJarData {
  address recipient;
  uint256 totalTips;
  uint64 lastTipAt;
  uint8 isActive;
}

library TipJar {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cms", name: "TipJar", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462636d7300000000000000000000005469704a617200000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x003d040014200801000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, uint256, uint64, uint8)
  Schema constant _valueSchema = Schema.wrap(0x003d0400611f0700000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "articleId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "recipient";
    fieldNames[1] = "totalTips";
    fieldNames[2] = "lastTipAt";
    fieldNames[3] = "isActive";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get recipient.
   */
  function getRecipient(bytes32 articleId) internal view returns (address recipient) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get recipient.
   */
  function _getRecipient(bytes32 articleId) internal view returns (address recipient) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set recipient.
   */
  function setRecipient(bytes32 articleId, address recipient) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((recipient)), _fieldLayout);
  }

  /**
   * @notice Set recipient.
   */
  function _setRecipient(bytes32 articleId, address recipient) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((recipient)), _fieldLayout);
  }

  /**
   * @notice Get totalTips.
   */
  function getTotalTips(bytes32 articleId) internal view returns (uint256 totalTips) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get totalTips.
   */
  function _getTotalTips(bytes32 articleId) internal view returns (uint256 totalTips) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set totalTips.
   */
  function setTotalTips(bytes32 articleId, uint256 totalTips) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalTips)), _fieldLayout);
  }

  /**
   * @notice Set totalTips.
   */
  function _setTotalTips(bytes32 articleId, uint256 totalTips) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((totalTips)), _fieldLayout);
  }

  /**
   * @notice Get lastTipAt.
   */
  function getLastTipAt(bytes32 articleId) internal view returns (uint64 lastTipAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Get lastTipAt.
   */
  function _getLastTipAt(bytes32 articleId) internal view returns (uint64 lastTipAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint64(bytes8(_blob)));
  }

  /**
   * @notice Set lastTipAt.
   */
  function setLastTipAt(bytes32 articleId, uint64 lastTipAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((lastTipAt)), _fieldLayout);
  }

  /**
   * @notice Set lastTipAt.
   */
  function _setLastTipAt(bytes32 articleId, uint64 lastTipAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((lastTipAt)), _fieldLayout);
  }

  /**
   * @notice Get isActive.
   */
  function getIsActive(bytes32 articleId) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get isActive.
   */
  function _getIsActive(bytes32 articleId) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set isActive.
   */
  function setIsActive(bytes32 articleId, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Set isActive.
   */
  function _setIsActive(bytes32 articleId, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 articleId) internal view returns (TipJarData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 articleId) internal view returns (TipJarData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 articleId, address recipient, uint256 totalTips, uint64 lastTipAt, uint8 isActive) internal {
    bytes memory _staticData = encodeStatic(recipient, totalTips, lastTipAt, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 articleId, address recipient, uint256 totalTips, uint64 lastTipAt, uint8 isActive) internal {
    bytes memory _staticData = encodeStatic(recipient, totalTips, lastTipAt, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 articleId, TipJarData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.recipient, _table.totalTips, _table.lastTipAt, _table.isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 articleId, TipJarData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.recipient, _table.totalTips, _table.lastTipAt, _table.isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (address recipient, uint256 totalTips, uint64 lastTipAt, uint8 isActive) {
    recipient = (address(Bytes.getBytes20(_blob, 0)));

    totalTips = (uint256(Bytes.getBytes32(_blob, 20)));

    lastTipAt = (uint64(Bytes.getBytes8(_blob, 52)));

    isActive = (uint8(Bytes.getBytes1(_blob, 60)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TipJarData memory _table) {
    (_table.recipient, _table.totalTips, _table.lastTipAt, _table.isActive) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 articleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 articleId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address recipient,
    uint256 totalTips,
    uint64 lastTipAt,
    uint8 isActive
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(recipient, totalTips, lastTipAt, isActive);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address recipient,
    uint256 totalTips,
    uint64 lastTipAt,
    uint8 isActive
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(recipient, totalTips, lastTipAt, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 articleId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = articleId;

    return _keyTuple;
  }
}
