// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TipSplitData {
  uint16 percentage;
  uint8 isActive;
}

library TipSplit {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "cms", name: "TipSplit", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462636d73000000000000000000000054697053706c69740000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0003020002010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, address)
  Schema constant _keySchema = Schema.wrap(0x003402005f610000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint16, uint8)
  Schema constant _valueSchema = Schema.wrap(0x0003020001000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "articleId";
    keyNames[1] = "recipient";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "percentage";
    fieldNames[1] = "isActive";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get percentage.
   */
  function getPercentage(bytes32 articleId, address recipient) internal view returns (uint16 percentage) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get percentage.
   */
  function _getPercentage(bytes32 articleId, address recipient) internal view returns (uint16 percentage) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set percentage.
   */
  function setPercentage(bytes32 articleId, address recipient, uint16 percentage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((percentage)), _fieldLayout);
  }

  /**
   * @notice Set percentage.
   */
  function _setPercentage(bytes32 articleId, address recipient, uint16 percentage) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((percentage)), _fieldLayout);
  }

  /**
   * @notice Get isActive.
   */
  function getIsActive(bytes32 articleId, address recipient) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get isActive.
   */
  function _getIsActive(bytes32 articleId, address recipient) internal view returns (uint8 isActive) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set isActive.
   */
  function setIsActive(bytes32 articleId, address recipient, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Set isActive.
   */
  function _setIsActive(bytes32 articleId, address recipient, uint8 isActive) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((isActive)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 articleId, address recipient) internal view returns (TipSplitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 articleId, address recipient) internal view returns (TipSplitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 articleId, address recipient, uint16 percentage, uint8 isActive) internal {
    bytes memory _staticData = encodeStatic(percentage, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 articleId, address recipient, uint16 percentage, uint8 isActive) internal {
    bytes memory _staticData = encodeStatic(percentage, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 articleId, address recipient, TipSplitData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.percentage, _table.isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 articleId, address recipient, TipSplitData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.percentage, _table.isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint16 percentage, uint8 isActive) {
    percentage = (uint16(Bytes.getBytes2(_blob, 0)));

    isActive = (uint8(Bytes.getBytes1(_blob, 2)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TipSplitData memory _table) {
    (_table.percentage, _table.isActive) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 articleId, address recipient) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 articleId, address recipient) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint16 percentage, uint8 isActive) internal pure returns (bytes memory) {
    return abi.encodePacked(percentage, isActive);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint16 percentage,
    uint8 isActive
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(percentage, isActive);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 articleId, address recipient) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = articleId;
    _keyTuple[1] = bytes32(uint256(uint160(recipient)));

    return _keyTuple;
  }
}
