// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ArticleCategories } from "./tables/ArticleCategories.sol";
import { ArticleMetadata, ArticleMetadataData } from "./tables/ArticleMetadata.sol";
import { Category } from "./tables/Category.sol";
import { Collection, CollectionData } from "./tables/Collection.sol";
import { CollectionPost } from "./tables/CollectionPost.sol";
import { NoteCategories } from "./tables/NoteCategories.sol";
import { NoteLink, NoteLinkData } from "./tables/NoteLink.sol";
import { Post, PostData } from "./tables/Post.sol";
import { PostToCollection } from "./tables/PostToCollection.sol";
import { WaypointGroup, WaypointGroupData } from "./tables/WaypointGroup.sol";
import { WaypointStep, WaypointStepData } from "./tables/WaypointStep.sol";
