// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { ChestOwner } from "./tables/ChestOwner.sol";
import { TradingChain } from "./tables/TradingChain.sol";
