// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ArticleCategories } from "./tables/ArticleCategories.sol";
import { Category } from "./tables/Category.sol";
import { Collection, CollectionData } from "./tables/Collection.sol";
import { CollectionPosts } from "./tables/CollectionPosts.sol";
import { Creators } from "./tables/Creators.sol";
import { DevContributors } from "./tables/DevContributors.sol";
import { Editors } from "./tables/Editors.sol";
import { IsArticle } from "./tables/IsArticle.sol";
import { IsEditor } from "./tables/IsEditor.sol";
import { IsEditorPublication } from "./tables/IsEditorPublication.sol";
import { IsNote } from "./tables/IsNote.sol";
import { LatestEditorPublication } from "./tables/LatestEditorPublication.sol";
import { NoteCategories } from "./tables/NoteCategories.sol";
import { Post, PostData } from "./tables/Post.sol";
import { PostAnchor, PostAnchorData } from "./tables/PostAnchor.sol";
import { TipCounter } from "./tables/TipCounter.sol";
import { TipDetails, TipDetailsData } from "./tables/TipDetails.sol";
import { Tipper } from "./tables/Tipper.sol";
import { TipReceipt, TipReceiptData } from "./tables/TipReceipt.sol";
import { Treasury } from "./tables/Treasury.sol";
