// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { NoteSystem } from "../../systems/NoteSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type NoteSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "rg_dd_0003", name: "NoteSystem" }))
NoteSystemType constant noteSystem = NoteSystemType.wrap(
  0x737972675f64645f30303033000000004e6f746553797374656d000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title NoteSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library NoteSystemLib {
  error NoteSystemLib_CallingFromRootSystem();

  function createNote(
    NoteSystemType self,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).createNote(title, content, categoryName);
  }

  function createNoteWithAnchor(
    NoteSystemType self,
    string memory title,
    string memory content,
    string memory categoryName,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    return
      CallWrapper(self.toResourceId(), address(0)).createNoteWithAnchor(
        title,
        content,
        categoryName,
        entityId,
        coordX,
        coordY,
        coordZ
      );
  }

  function updateNote(
    NoteSystemType self,
    bytes32 noteId,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).updateNote(noteId, title, content, categoryName);
  }

  function deleteNote(NoteSystemType self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).deleteNote(noteId);
  }

  function createNoteAnchor(
    NoteSystemType self,
    bytes32 noteId,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).createNoteAnchor(noteId, entityId, coordX, coordY, coordZ);
  }

  function removeNoteAnchor(NoteSystemType self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).removeNoteAnchor(noteId);
  }

  function createNote(
    CallWrapper memory self,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createNote_string_string_string.createNote,
      (title, content, categoryName)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function createNoteWithAnchor(
    CallWrapper memory self,
    string memory title,
    string memory content,
    string memory categoryName,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createNoteWithAnchor_string_string_string_bytes32_int32_int32_int32.createNoteWithAnchor,
      (title, content, categoryName, entityId, coordX, coordY, coordZ)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function updateNote(
    CallWrapper memory self,
    bytes32 noteId,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateNote_bytes32_string_string_string.updateNote,
      (noteId, title, content, categoryName)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function deleteNote(CallWrapper memory self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_deleteNote_bytes32.deleteNote, (noteId));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function createNoteAnchor(
    CallWrapper memory self,
    bytes32 noteId,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createNoteAnchor_bytes32_bytes32_int32_int32_int32.createNoteAnchor,
      (noteId, entityId, coordX, coordY, coordZ)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function removeNoteAnchor(CallWrapper memory self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert NoteSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeNoteAnchor_bytes32.removeNoteAnchor, (noteId));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function createNote(
    RootCallWrapper memory self,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _createNote_string_string_string.createNote,
      (title, content, categoryName)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function createNoteWithAnchor(
    RootCallWrapper memory self,
    string memory title,
    string memory content,
    string memory categoryName,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _createNoteWithAnchor_string_string_string_bytes32_int32_int32_int32.createNoteWithAnchor,
      (title, content, categoryName, entityId, coordX, coordY, coordZ)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function updateNote(
    RootCallWrapper memory self,
    bytes32 noteId,
    string memory title,
    string memory content,
    string memory categoryName
  ) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _updateNote_bytes32_string_string_string.updateNote,
      (noteId, title, content, categoryName)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function deleteNote(RootCallWrapper memory self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_deleteNote_bytes32.deleteNote, (noteId));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function createNoteAnchor(
    RootCallWrapper memory self,
    bytes32 noteId,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _createNoteAnchor_bytes32_bytes32_int32_int32_int32.createNoteAnchor,
      (noteId, entityId, coordX, coordY, coordZ)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function removeNoteAnchor(RootCallWrapper memory self, bytes32 noteId) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_removeNoteAnchor_bytes32.removeNoteAnchor, (noteId));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function callFrom(NoteSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(NoteSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(NoteSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(NoteSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(NoteSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (NoteSystemType) {
    return NoteSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(NoteSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createNote_string_string_string {
  function createNote(string memory title, string memory content, string memory categoryName) external;
}

interface _createNoteWithAnchor_string_string_string_bytes32_int32_int32_int32 {
  function createNoteWithAnchor(
    string memory title,
    string memory content,
    string memory categoryName,
    bytes32 entityId,
    int32 coordX,
    int32 coordY,
    int32 coordZ
  ) external;
}

interface _updateNote_bytes32_string_string_string {
  function updateNote(bytes32 noteId, string memory title, string memory content, string memory categoryName) external;
}

interface _deleteNote_bytes32 {
  function deleteNote(bytes32 noteId) external;
}

interface _createNoteAnchor_bytes32_bytes32_int32_int32_int32 {
  function createNoteAnchor(bytes32 noteId, bytes32 entityId, int32 coordX, int32 coordY, int32 coordZ) external;
}

interface _removeNoteAnchor_bytes32 {
  function removeNoteAnchor(bytes32 noteId) external;
}

using NoteSystemLib for NoteSystemType global;
using NoteSystemLib for CallWrapper global;
using NoteSystemLib for RootCallWrapper global;
