// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TipSystem } from "../../systems/TipSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type TipSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "thedailydust", name: "TipSystem" }))
TipSystemType constant tipSystem = TipSystemType.wrap(
  0x73797468656461696c7964757374000054697053797374656d00000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title TipSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library TipSystemLib {
  error TipSystemLib_CallingFromRootSystem();

  function tipPost(
    TipSystemType self,
    bytes32 postId,
    address tokenAddress,
    uint256 amount
  ) internal returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).tipPost(postId, tokenAddress, amount);
  }

  function tipPost(
    CallWrapper memory self,
    bytes32 postId,
    address tokenAddress,
    uint256 amount
  ) internal returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_tipPost_bytes32_address_uint256.tipPost, (postId, tokenAddress, amount));

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function tipPost(
    RootCallWrapper memory self,
    bytes32 postId,
    address tokenAddress,
    uint256 amount
  ) internal returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_tipPost_bytes32_address_uint256.tipPost, (postId, tokenAddress, amount));

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function callFrom(TipSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(TipSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(TipSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(TipSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(TipSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (TipSystemType) {
    return TipSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(TipSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _tipPost_bytes32_address_uint256 {
  function tipPost(bytes32 postId, address tokenAddress, uint256 amount) external;
}

using TipSystemLib for TipSystemType global;
using TipSystemLib for CallWrapper global;
using TipSystemLib for RootCallWrapper global;
