// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { FeaturedSystem } from "../../systems/FeaturedSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type FeaturedSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "dailydust", name: "FeaturedSystem" }))
FeaturedSystemType constant featuredSystem = FeaturedSystemType.wrap(
  0x73796461696c79647573740000000000466561747572656453797374656d0000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title FeaturedSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library FeaturedSystemLib {
  error FeaturedSystemLib_CallingFromRootSystem();

  function featureArticle(FeaturedSystemType self, uint32 date, uint8 slot, bytes32 articleId) internal {
    return CallWrapper(self.toResourceId(), address(0)).featureArticle(date, slot, articleId);
  }

  function unfeatureArticle(FeaturedSystemType self, uint32 date, uint8 slot) internal {
    return CallWrapper(self.toResourceId(), address(0)).unfeatureArticle(date, slot);
  }

  function setDailyDigest(FeaturedSystemType self, uint32 date, bytes32[] memory articleIds) internal {
    return CallWrapper(self.toResourceId(), address(0)).setDailyDigest(date, articleIds);
  }

  function moveFeaturedArticle(FeaturedSystemType self, uint32 date, uint8 fromSlot, uint8 toSlot) internal {
    return CallWrapper(self.toResourceId(), address(0)).moveFeaturedArticle(date, fromSlot, toSlot);
  }

  function swapFeaturedArticles(FeaturedSystemType self, uint32 date, uint8 slot1, uint8 slot2) internal {
    return CallWrapper(self.toResourceId(), address(0)).swapFeaturedArticles(date, slot1, slot2);
  }

  function getFeaturedArticle(
    FeaturedSystemType self,
    uint32 date,
    uint8 slot
  ) internal view returns (bytes32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getFeaturedArticle(date, slot);
  }

  function getDailyDigest(FeaturedSystemType self, uint32 date) internal view returns (bytes32[10] memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getDailyDigest(date);
  }

  function isArticleFeatured(
    FeaturedSystemType self,
    bytes32 articleId,
    uint32 date
  ) internal view returns (bool __auxRet0, uint8 __auxRet1) {
    return CallWrapper(self.toResourceId(), address(0)).isArticleFeatured(articleId, date);
  }

  function getTodayDate(FeaturedSystemType self) internal view returns (uint32 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getTodayDate();
  }

  function getFeaturedCount(FeaturedSystemType self, uint32 date) internal view returns (uint8 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getFeaturedCount(date);
  }

  function copyDailyDigest(FeaturedSystemType self, uint32 fromDate, uint32 toDate) internal {
    return CallWrapper(self.toResourceId(), address(0)).copyDailyDigest(fromDate, toDate);
  }

  function featureArticle(CallWrapper memory self, uint32 date, uint8 slot, bytes32 articleId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _featureArticle_uint32_uint8_bytes32.featureArticle,
      (date, slot, articleId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function unfeatureArticle(CallWrapper memory self, uint32 date, uint8 slot) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_unfeatureArticle_uint32_uint8.unfeatureArticle, (date, slot));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setDailyDigest(CallWrapper memory self, uint32 date, bytes32[] memory articleIds) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setDailyDigest_uint32_bytes32Array.setDailyDigest, (date, articleIds));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function moveFeaturedArticle(CallWrapper memory self, uint32 date, uint8 fromSlot, uint8 toSlot) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _moveFeaturedArticle_uint32_uint8_uint8.moveFeaturedArticle,
      (date, fromSlot, toSlot)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function swapFeaturedArticles(CallWrapper memory self, uint32 date, uint8 slot1, uint8 slot2) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _swapFeaturedArticles_uint32_uint8_uint8.swapFeaturedArticles,
      (date, slot1, slot2)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getFeaturedArticle(
    CallWrapper memory self,
    uint32 date,
    uint8 slot
  ) internal view returns (bytes32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getFeaturedArticle_uint32_uint8.getFeaturedArticle, (date, slot));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function getDailyDigest(CallWrapper memory self, uint32 date) internal view returns (bytes32[10] memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getDailyDigest_uint32.getDailyDigest, (date));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32[10]));
    }
  }

  function isArticleFeatured(
    CallWrapper memory self,
    bytes32 articleId,
    uint32 date
  ) internal view returns (bool __auxRet0, uint8 __auxRet1) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_isArticleFeatured_bytes32_uint32.isArticleFeatured, (articleId, date));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool, uint8));
    }
  }

  function getTodayDate(CallWrapper memory self) internal view returns (uint32 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getTodayDate.getTodayDate, ());
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint32));
    }
  }

  function getFeaturedCount(CallWrapper memory self, uint32 date) internal view returns (uint8 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getFeaturedCount_uint32.getFeaturedCount, (date));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint8));
    }
  }

  function copyDailyDigest(CallWrapper memory self, uint32 fromDate, uint32 toDate) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert FeaturedSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_copyDailyDigest_uint32_uint32.copyDailyDigest, (fromDate, toDate));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function featureArticle(RootCallWrapper memory self, uint32 date, uint8 slot, bytes32 articleId) internal {
    bytes memory systemCall = abi.encodeCall(
      _featureArticle_uint32_uint8_bytes32.featureArticle,
      (date, slot, articleId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function unfeatureArticle(RootCallWrapper memory self, uint32 date, uint8 slot) internal {
    bytes memory systemCall = abi.encodeCall(_unfeatureArticle_uint32_uint8.unfeatureArticle, (date, slot));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setDailyDigest(RootCallWrapper memory self, uint32 date, bytes32[] memory articleIds) internal {
    bytes memory systemCall = abi.encodeCall(_setDailyDigest_uint32_bytes32Array.setDailyDigest, (date, articleIds));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function moveFeaturedArticle(RootCallWrapper memory self, uint32 date, uint8 fromSlot, uint8 toSlot) internal {
    bytes memory systemCall = abi.encodeCall(
      _moveFeaturedArticle_uint32_uint8_uint8.moveFeaturedArticle,
      (date, fromSlot, toSlot)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function swapFeaturedArticles(RootCallWrapper memory self, uint32 date, uint8 slot1, uint8 slot2) internal {
    bytes memory systemCall = abi.encodeCall(
      _swapFeaturedArticles_uint32_uint8_uint8.swapFeaturedArticles,
      (date, slot1, slot2)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getFeaturedArticle(
    RootCallWrapper memory self,
    uint32 date,
    uint8 slot
  ) internal view returns (bytes32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getFeaturedArticle_uint32_uint8.getFeaturedArticle, (date, slot));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32));
    }
  }

  function getDailyDigest(
    RootCallWrapper memory self,
    uint32 date
  ) internal view returns (bytes32[10] memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getDailyDigest_uint32.getDailyDigest, (date));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bytes32[10]));
    }
  }

  function isArticleFeatured(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint32 date
  ) internal view returns (bool __auxRet0, uint8 __auxRet1) {
    bytes memory systemCall = abi.encodeCall(_isArticleFeatured_bytes32_uint32.isArticleFeatured, (articleId, date));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool, uint8));
    }
  }

  function getTodayDate(RootCallWrapper memory self) internal view returns (uint32 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getTodayDate.getTodayDate, ());

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint32));
    }
  }

  function getFeaturedCount(RootCallWrapper memory self, uint32 date) internal view returns (uint8 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getFeaturedCount_uint32.getFeaturedCount, (date));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint8));
    }
  }

  function copyDailyDigest(RootCallWrapper memory self, uint32 fromDate, uint32 toDate) internal {
    bytes memory systemCall = abi.encodeCall(_copyDailyDigest_uint32_uint32.copyDailyDigest, (fromDate, toDate));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(FeaturedSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(FeaturedSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(FeaturedSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(FeaturedSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(FeaturedSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (FeaturedSystemType) {
    return FeaturedSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(FeaturedSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _featureArticle_uint32_uint8_bytes32 {
  function featureArticle(uint32 date, uint8 slot, bytes32 articleId) external;
}

interface _unfeatureArticle_uint32_uint8 {
  function unfeatureArticle(uint32 date, uint8 slot) external;
}

interface _setDailyDigest_uint32_bytes32Array {
  function setDailyDigest(uint32 date, bytes32[] memory articleIds) external;
}

interface _moveFeaturedArticle_uint32_uint8_uint8 {
  function moveFeaturedArticle(uint32 date, uint8 fromSlot, uint8 toSlot) external;
}

interface _swapFeaturedArticles_uint32_uint8_uint8 {
  function swapFeaturedArticles(uint32 date, uint8 slot1, uint8 slot2) external;
}

interface _getFeaturedArticle_uint32_uint8 {
  function getFeaturedArticle(uint32 date, uint8 slot) external;
}

interface _getDailyDigest_uint32 {
  function getDailyDigest(uint32 date) external;
}

interface _isArticleFeatured_bytes32_uint32 {
  function isArticleFeatured(bytes32 articleId, uint32 date) external;
}

interface _getTodayDate {
  function getTodayDate() external;
}

interface _getFeaturedCount_uint32 {
  function getFeaturedCount(uint32 date) external;
}

interface _copyDailyDigest_uint32_uint32 {
  function copyDailyDigest(uint32 fromDate, uint32 toDate) external;
}

using FeaturedSystemLib for FeaturedSystemType global;
using FeaturedSystemLib for CallWrapper global;
using FeaturedSystemLib for RootCallWrapper global;
