// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ArticleSystem } from "../../systems/ArticleSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ArticleSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cms", name: "ArticleSystem" }))
ArticleSystemType constant articleSystem = ArticleSystemType.wrap(
  0x7379636d73000000000000000000000041727469636c6553797374656d000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ArticleSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ArticleSystemLib {
  error ArticleSystemLib_CallingFromRootSystem();

  function createArticle(
    ArticleSystemType self,
    bytes32 articleId,
    uint8 articleType,
    bytes32 category,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createArticle(
        articleId,
        articleType,
        category,
        title,
        kicker,
        content,
        headerImageUrl
      );
  }

  function updateArticle(
    ArticleSystemType self,
    bytes32 articleId,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).updateArticle(articleId, title, kicker, content, headerImageUrl);
  }

  function updateCategory(ArticleSystemType self, bytes32 articleId, bytes32 newCategory) internal {
    return CallWrapper(self.toResourceId(), address(0)).updateCategory(articleId, newCategory);
  }

  function deleteArticle(ArticleSystemType self, bytes32 articleId) internal {
    return CallWrapper(self.toResourceId(), address(0)).deleteArticle(articleId);
  }

  function createArticleLink(
    ArticleSystemType self,
    bytes32 articleId,
    bytes32 entityId,
    uint8 linkType,
    int32 coordX,
    int32 coordY,
    int32 coordZ,
    string memory extra
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createArticleLink(
        articleId,
        entityId,
        linkType,
        coordX,
        coordY,
        coordZ,
        extra
      );
  }

  function removeArticleLink(ArticleSystemType self, bytes32 articleId, bytes32 entityId) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeArticleLink(articleId, entityId);
  }

  function transferOwnership(ArticleSystemType self, bytes32 articleId, address newOwner) internal {
    return CallWrapper(self.toResourceId(), address(0)).transferOwnership(articleId, newOwner);
  }

  function createArticle(
    CallWrapper memory self,
    bytes32 articleId,
    uint8 articleType,
    bytes32 category,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createArticle_bytes32_uint8_bytes32_string_string_string_string.createArticle,
      (articleId, articleType, category, title, kicker, content, headerImageUrl)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateArticle(
    CallWrapper memory self,
    bytes32 articleId,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateArticle_bytes32_string_string_string_string.updateArticle,
      (articleId, title, kicker, content, headerImageUrl)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateCategory(CallWrapper memory self, bytes32 articleId, bytes32 newCategory) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_updateCategory_bytes32_bytes32.updateCategory, (articleId, newCategory));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function deleteArticle(CallWrapper memory self, bytes32 articleId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_deleteArticle_bytes32.deleteArticle, (articleId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createArticleLink(
    CallWrapper memory self,
    bytes32 articleId,
    bytes32 entityId,
    uint8 linkType,
    int32 coordX,
    int32 coordY,
    int32 coordZ,
    string memory extra
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createArticleLink_bytes32_bytes32_uint8_int32_int32_int32_string.createArticleLink,
      (articleId, entityId, linkType, coordX, coordY, coordZ, extra)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeArticleLink(CallWrapper memory self, bytes32 articleId, bytes32 entityId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _removeArticleLink_bytes32_bytes32.removeArticleLink,
      (articleId, entityId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function transferOwnership(CallWrapper memory self, bytes32 articleId, address newOwner) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ArticleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _transferOwnership_bytes32_address.transferOwnership,
      (articleId, newOwner)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createArticle(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint8 articleType,
    bytes32 category,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createArticle_bytes32_uint8_bytes32_string_string_string_string.createArticle,
      (articleId, articleType, category, title, kicker, content, headerImageUrl)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateArticle(
    RootCallWrapper memory self,
    bytes32 articleId,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _updateArticle_bytes32_string_string_string_string.updateArticle,
      (articleId, title, kicker, content, headerImageUrl)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateCategory(RootCallWrapper memory self, bytes32 articleId, bytes32 newCategory) internal {
    bytes memory systemCall = abi.encodeCall(_updateCategory_bytes32_bytes32.updateCategory, (articleId, newCategory));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function deleteArticle(RootCallWrapper memory self, bytes32 articleId) internal {
    bytes memory systemCall = abi.encodeCall(_deleteArticle_bytes32.deleteArticle, (articleId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function createArticleLink(
    RootCallWrapper memory self,
    bytes32 articleId,
    bytes32 entityId,
    uint8 linkType,
    int32 coordX,
    int32 coordY,
    int32 coordZ,
    string memory extra
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createArticleLink_bytes32_bytes32_uint8_int32_int32_int32_string.createArticleLink,
      (articleId, entityId, linkType, coordX, coordY, coordZ, extra)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeArticleLink(RootCallWrapper memory self, bytes32 articleId, bytes32 entityId) internal {
    bytes memory systemCall = abi.encodeCall(
      _removeArticleLink_bytes32_bytes32.removeArticleLink,
      (articleId, entityId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function transferOwnership(RootCallWrapper memory self, bytes32 articleId, address newOwner) internal {
    bytes memory systemCall = abi.encodeCall(
      _transferOwnership_bytes32_address.transferOwnership,
      (articleId, newOwner)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ArticleSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ArticleSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ArticleSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ArticleSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ArticleSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ArticleSystemType) {
    return ArticleSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ArticleSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createArticle_bytes32_uint8_bytes32_string_string_string_string {
  function createArticle(
    bytes32 articleId,
    uint8 articleType,
    bytes32 category,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) external;
}

interface _updateArticle_bytes32_string_string_string_string {
  function updateArticle(
    bytes32 articleId,
    string memory title,
    string memory kicker,
    string memory content,
    string memory headerImageUrl
  ) external;
}

interface _updateCategory_bytes32_bytes32 {
  function updateCategory(bytes32 articleId, bytes32 newCategory) external;
}

interface _deleteArticle_bytes32 {
  function deleteArticle(bytes32 articleId) external;
}

interface _createArticleLink_bytes32_bytes32_uint8_int32_int32_int32_string {
  function createArticleLink(
    bytes32 articleId,
    bytes32 entityId,
    uint8 linkType,
    int32 coordX,
    int32 coordY,
    int32 coordZ,
    string memory extra
  ) external;
}

interface _removeArticleLink_bytes32_bytes32 {
  function removeArticleLink(bytes32 articleId, bytes32 entityId) external;
}

interface _transferOwnership_bytes32_address {
  function transferOwnership(bytes32 articleId, address newOwner) external;
}

using ArticleSystemLib for ArticleSystemType global;
using ArticleSystemLib for CallWrapper global;
using ArticleSystemLib for RootCallWrapper global;
