// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CollectionSystem } from "../../systems/CollectionSystem.sol";
import { CollectionData } from "../tables/Collection.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type CollectionSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cms", name: "CollectionSystem" }))
CollectionSystemType constant collectionSystem = CollectionSystemType.wrap(
  0x7379636d730000000000000000000000436f6c6c656374696f6e53797374656d
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title CollectionSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library CollectionSystemLib {
  error CollectionSystemLib_CallingFromRootSystem();

  function createCollection(
    CollectionSystemType self,
    bytes32 collectionId,
    uint8 collectionType,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createCollection(
        collectionId,
        collectionType,
        title,
        description,
        headerImageUrl,
        featured
      );
  }

  function updateCollection(
    CollectionSystemType self,
    bytes32 collectionId,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).updateCollection(
        collectionId,
        title,
        description,
        headerImageUrl,
        featured
      );
  }

  function deleteCollection(CollectionSystemType self, bytes32 collectionId) internal {
    return CallWrapper(self.toResourceId(), address(0)).deleteCollection(collectionId);
  }

  function addArticleToCollection(
    CollectionSystemType self,
    bytes32 collectionId,
    bytes32 articleId,
    uint16 index
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).addArticleToCollection(collectionId, articleId, index);
  }

  function removeArticleFromCollection(CollectionSystemType self, bytes32 collectionId, uint16 index) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeArticleFromCollection(collectionId, index);
  }

  function moveArticleInCollection(
    CollectionSystemType self,
    bytes32 collectionId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).moveArticleInCollection(collectionId, fromIndex, toIndex);
  }

  function transferCollectionOwnership(CollectionSystemType self, bytes32 collectionId, address newOwner) internal {
    return CallWrapper(self.toResourceId(), address(0)).transferCollectionOwnership(collectionId, newOwner);
  }

  function getCollection(
    CollectionSystemType self,
    bytes32 collectionId
  ) internal view returns (CollectionData memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getCollection(collectionId);
  }

  function isArticleInCollection(
    CollectionSystemType self,
    bytes32 articleId,
    bytes32 collectionId
  ) internal view returns (bool __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).isArticleInCollection(articleId, collectionId);
  }

  function createCollection(
    CallWrapper memory self,
    bytes32 collectionId,
    uint8 collectionType,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createCollection_bytes32_uint8_string_string_string_bool.createCollection,
      (collectionId, collectionType, title, description, headerImageUrl, featured)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateCollection(
    CallWrapper memory self,
    bytes32 collectionId,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateCollection_bytes32_string_string_string_bool.updateCollection,
      (collectionId, title, description, headerImageUrl, featured)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function deleteCollection(CallWrapper memory self, bytes32 collectionId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_deleteCollection_bytes32.deleteCollection, (collectionId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addArticleToCollection(
    CallWrapper memory self,
    bytes32 collectionId,
    bytes32 articleId,
    uint16 index
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _addArticleToCollection_bytes32_bytes32_uint16.addArticleToCollection,
      (collectionId, articleId, index)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeArticleFromCollection(CallWrapper memory self, bytes32 collectionId, uint16 index) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _removeArticleFromCollection_bytes32_uint16.removeArticleFromCollection,
      (collectionId, index)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function moveArticleInCollection(
    CallWrapper memory self,
    bytes32 collectionId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _moveArticleInCollection_bytes32_uint16_uint16.moveArticleInCollection,
      (collectionId, fromIndex, toIndex)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function transferCollectionOwnership(CallWrapper memory self, bytes32 collectionId, address newOwner) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _transferCollectionOwnership_bytes32_address.transferCollectionOwnership,
      (collectionId, newOwner)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getCollection(
    CallWrapper memory self,
    bytes32 collectionId
  ) internal view returns (CollectionData memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getCollection_bytes32.getCollection, (collectionId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (CollectionData));
    }
  }

  function isArticleInCollection(
    CallWrapper memory self,
    bytes32 articleId,
    bytes32 collectionId
  ) internal view returns (bool __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CollectionSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _isArticleInCollection_bytes32_bytes32.isArticleInCollection,
      (articleId, collectionId)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function createCollection(
    RootCallWrapper memory self,
    bytes32 collectionId,
    uint8 collectionType,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createCollection_bytes32_uint8_string_string_string_bool.createCollection,
      (collectionId, collectionType, title, description, headerImageUrl, featured)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateCollection(
    RootCallWrapper memory self,
    bytes32 collectionId,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _updateCollection_bytes32_string_string_string_bool.updateCollection,
      (collectionId, title, description, headerImageUrl, featured)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function deleteCollection(RootCallWrapper memory self, bytes32 collectionId) internal {
    bytes memory systemCall = abi.encodeCall(_deleteCollection_bytes32.deleteCollection, (collectionId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function addArticleToCollection(
    RootCallWrapper memory self,
    bytes32 collectionId,
    bytes32 articleId,
    uint16 index
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _addArticleToCollection_bytes32_bytes32_uint16.addArticleToCollection,
      (collectionId, articleId, index)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeArticleFromCollection(RootCallWrapper memory self, bytes32 collectionId, uint16 index) internal {
    bytes memory systemCall = abi.encodeCall(
      _removeArticleFromCollection_bytes32_uint16.removeArticleFromCollection,
      (collectionId, index)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function moveArticleInCollection(
    RootCallWrapper memory self,
    bytes32 collectionId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _moveArticleInCollection_bytes32_uint16_uint16.moveArticleInCollection,
      (collectionId, fromIndex, toIndex)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function transferCollectionOwnership(RootCallWrapper memory self, bytes32 collectionId, address newOwner) internal {
    bytes memory systemCall = abi.encodeCall(
      _transferCollectionOwnership_bytes32_address.transferCollectionOwnership,
      (collectionId, newOwner)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getCollection(
    RootCallWrapper memory self,
    bytes32 collectionId
  ) internal view returns (CollectionData memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getCollection_bytes32.getCollection, (collectionId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (CollectionData));
    }
  }

  function isArticleInCollection(
    RootCallWrapper memory self,
    bytes32 articleId,
    bytes32 collectionId
  ) internal view returns (bool __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _isArticleInCollection_bytes32_bytes32.isArticleInCollection,
      (articleId, collectionId)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function callFrom(CollectionSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(CollectionSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(CollectionSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(CollectionSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(CollectionSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (CollectionSystemType) {
    return CollectionSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(CollectionSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createCollection_bytes32_uint8_string_string_string_bool {
  function createCollection(
    bytes32 collectionId,
    uint8 collectionType,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) external;
}

interface _updateCollection_bytes32_string_string_string_bool {
  function updateCollection(
    bytes32 collectionId,
    string memory title,
    string memory description,
    string memory headerImageUrl,
    bool featured
  ) external;
}

interface _deleteCollection_bytes32 {
  function deleteCollection(bytes32 collectionId) external;
}

interface _addArticleToCollection_bytes32_bytes32_uint16 {
  function addArticleToCollection(bytes32 collectionId, bytes32 articleId, uint16 index) external;
}

interface _removeArticleFromCollection_bytes32_uint16 {
  function removeArticleFromCollection(bytes32 collectionId, uint16 index) external;
}

interface _moveArticleInCollection_bytes32_uint16_uint16 {
  function moveArticleInCollection(bytes32 collectionId, uint16 fromIndex, uint16 toIndex) external;
}

interface _transferCollectionOwnership_bytes32_address {
  function transferCollectionOwnership(bytes32 collectionId, address newOwner) external;
}

interface _getCollection_bytes32 {
  function getCollection(bytes32 collectionId) external;
}

interface _isArticleInCollection_bytes32_bytes32 {
  function isArticleInCollection(bytes32 articleId, bytes32 collectionId) external;
}

using CollectionSystemLib for CollectionSystemType global;
using CollectionSystemLib for CallWrapper global;
using CollectionSystemLib for RootCallWrapper global;
