// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ReferenceSystem } from "../../systems/ReferenceSystem.sol";
import { ArticleReferenceData } from "../tables/ArticleReference.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ReferenceSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cms", name: "ReferenceSystem" }))
ReferenceSystemType constant referenceSystem = ReferenceSystemType.wrap(
  0x7379636d7300000000000000000000005265666572656e636553797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ReferenceSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ReferenceSystemLib {
  error ReferenceSystemLib_CallingFromRootSystem();

  function createReference(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 referenceType,
    string memory context
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createReference(fromArticleId, toArticleId, referenceType, context);
  }

  function updateReference(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 newReferenceType,
    string memory newContext
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).updateReference(
        fromArticleId,
        toArticleId,
        newReferenceType,
        newContext
      );
  }

  function removeReference(ReferenceSystemType self, bytes32 fromArticleId, bytes32 toArticleId) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeReference(fromArticleId, toArticleId);
  }

  function createMultipleReferences(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32[] memory toArticleIds,
    uint8[] memory referenceTypes,
    string[] memory contexts
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createMultipleReferences(
        fromArticleId,
        toArticleIds,
        referenceTypes,
        contexts
      );
  }

  function getReference(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (ArticleReferenceData memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getReference(fromArticleId, toArticleId);
  }

  function referenceExists(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (bool __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).referenceExists(fromArticleId, toArticleId);
  }

  function getReferenceType(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (uint8 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getReferenceType(fromArticleId, toArticleId);
  }

  function getReferenceContext(
    ReferenceSystemType self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (string memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getReferenceContext(fromArticleId, toArticleId);
  }

  function createMutualReference(
    ReferenceSystemType self,
    bytes32 articleId1,
    bytes32 articleId2,
    uint8 referenceType,
    string memory context1,
    string memory context2
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createMutualReference(
        articleId1,
        articleId2,
        referenceType,
        context1,
        context2
      );
  }

  function getReferenceTypeName(
    ReferenceSystemType self,
    uint8 referenceType
  ) internal view returns (string memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getReferenceTypeName(referenceType);
  }

  function createReference(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 referenceType,
    string memory context
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createReference_bytes32_bytes32_uint8_string.createReference,
      (fromArticleId, toArticleId, referenceType, context)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateReference(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 newReferenceType,
    string memory newContext
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateReference_bytes32_bytes32_uint8_string.updateReference,
      (fromArticleId, toArticleId, newReferenceType, newContext)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeReference(CallWrapper memory self, bytes32 fromArticleId, bytes32 toArticleId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _removeReference_bytes32_bytes32.removeReference,
      (fromArticleId, toArticleId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function createMultipleReferences(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32[] memory toArticleIds,
    uint8[] memory referenceTypes,
    string[] memory contexts
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createMultipleReferences_bytes32_bytes32Array_uint8Array_stringArray.createMultipleReferences,
      (fromArticleId, toArticleIds, referenceTypes, contexts)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getReference(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (ArticleReferenceData memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getReference_bytes32_bytes32.getReference, (fromArticleId, toArticleId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (ArticleReferenceData));
    }
  }

  function referenceExists(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (bool __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _referenceExists_bytes32_bytes32.referenceExists,
      (fromArticleId, toArticleId)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function getReferenceType(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (uint8 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _getReferenceType_bytes32_bytes32.getReferenceType,
      (fromArticleId, toArticleId)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint8));
    }
  }

  function getReferenceContext(
    CallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (string memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _getReferenceContext_bytes32_bytes32.getReferenceContext,
      (fromArticleId, toArticleId)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (string));
    }
  }

  function createMutualReference(
    CallWrapper memory self,
    bytes32 articleId1,
    bytes32 articleId2,
    uint8 referenceType,
    string memory context1,
    string memory context2
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createMutualReference_bytes32_bytes32_uint8_string_string.createMutualReference,
      (articleId1, articleId2, referenceType, context1, context2)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getReferenceTypeName(
    CallWrapper memory self,
    uint8 referenceType
  ) internal view returns (string memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ReferenceSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getReferenceTypeName_uint8.getReferenceTypeName, (referenceType));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (string));
    }
  }

  function createReference(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 referenceType,
    string memory context
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createReference_bytes32_bytes32_uint8_string.createReference,
      (fromArticleId, toArticleId, referenceType, context)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateReference(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 newReferenceType,
    string memory newContext
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _updateReference_bytes32_bytes32_uint8_string.updateReference,
      (fromArticleId, toArticleId, newReferenceType, newContext)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeReference(RootCallWrapper memory self, bytes32 fromArticleId, bytes32 toArticleId) internal {
    bytes memory systemCall = abi.encodeCall(
      _removeReference_bytes32_bytes32.removeReference,
      (fromArticleId, toArticleId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function createMultipleReferences(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32[] memory toArticleIds,
    uint8[] memory referenceTypes,
    string[] memory contexts
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createMultipleReferences_bytes32_bytes32Array_uint8Array_stringArray.createMultipleReferences,
      (fromArticleId, toArticleIds, referenceTypes, contexts)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getReference(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (ArticleReferenceData memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getReference_bytes32_bytes32.getReference, (fromArticleId, toArticleId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (ArticleReferenceData));
    }
  }

  function referenceExists(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (bool __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _referenceExists_bytes32_bytes32.referenceExists,
      (fromArticleId, toArticleId)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function getReferenceType(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (uint8 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _getReferenceType_bytes32_bytes32.getReferenceType,
      (fromArticleId, toArticleId)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint8));
    }
  }

  function getReferenceContext(
    RootCallWrapper memory self,
    bytes32 fromArticleId,
    bytes32 toArticleId
  ) internal view returns (string memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _getReferenceContext_bytes32_bytes32.getReferenceContext,
      (fromArticleId, toArticleId)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (string));
    }
  }

  function createMutualReference(
    RootCallWrapper memory self,
    bytes32 articleId1,
    bytes32 articleId2,
    uint8 referenceType,
    string memory context1,
    string memory context2
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createMutualReference_bytes32_bytes32_uint8_string_string.createMutualReference,
      (articleId1, articleId2, referenceType, context1, context2)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getReferenceTypeName(
    RootCallWrapper memory self,
    uint8 referenceType
  ) internal view returns (string memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getReferenceTypeName_uint8.getReferenceTypeName, (referenceType));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (string));
    }
  }

  function callFrom(ReferenceSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ReferenceSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ReferenceSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ReferenceSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ReferenceSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ReferenceSystemType) {
    return ReferenceSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ReferenceSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createReference_bytes32_bytes32_uint8_string {
  function createReference(
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 referenceType,
    string memory context
  ) external;
}

interface _updateReference_bytes32_bytes32_uint8_string {
  function updateReference(
    bytes32 fromArticleId,
    bytes32 toArticleId,
    uint8 newReferenceType,
    string memory newContext
  ) external;
}

interface _removeReference_bytes32_bytes32 {
  function removeReference(bytes32 fromArticleId, bytes32 toArticleId) external;
}

interface _createMultipleReferences_bytes32_bytes32Array_uint8Array_stringArray {
  function createMultipleReferences(
    bytes32 fromArticleId,
    bytes32[] memory toArticleIds,
    uint8[] memory referenceTypes,
    string[] memory contexts
  ) external;
}

interface _getReference_bytes32_bytes32 {
  function getReference(bytes32 fromArticleId, bytes32 toArticleId) external;
}

interface _referenceExists_bytes32_bytes32 {
  function referenceExists(bytes32 fromArticleId, bytes32 toArticleId) external;
}

interface _getReferenceType_bytes32_bytes32 {
  function getReferenceType(bytes32 fromArticleId, bytes32 toArticleId) external;
}

interface _getReferenceContext_bytes32_bytes32 {
  function getReferenceContext(bytes32 fromArticleId, bytes32 toArticleId) external;
}

interface _createMutualReference_bytes32_bytes32_uint8_string_string {
  function createMutualReference(
    bytes32 articleId1,
    bytes32 articleId2,
    uint8 referenceType,
    string memory context1,
    string memory context2
  ) external;
}

interface _getReferenceTypeName_uint8 {
  function getReferenceTypeName(uint8 referenceType) external;
}

using ReferenceSystemLib for ReferenceSystemType global;
using ReferenceSystemLib for CallWrapper global;
using ReferenceSystemLib for RootCallWrapper global;
