// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TipSystem } from "../../systems/TipSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type TipSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cms", name: "TipSystem" }))
TipSystemType constant tipSystem = TipSystemType.wrap(
  0x7379636d73000000000000000000000054697053797374656d00000000000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title TipSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library TipSystemLib {
  error TipSystemLib_CallingFromRootSystem();

  function tipArticle(
    TipSystemType self,
    bytes32 articleId,
    address currency,
    uint256 amount,
    string memory message
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).tipArticle(articleId, currency, amount, message);
  }

  function updateTipJar(TipSystemType self, bytes32 articleId, address newRecipient) internal {
    return CallWrapper(self.toResourceId(), address(0)).updateTipJar(articleId, newRecipient);
  }

  function setTipJarActive(TipSystemType self, bytes32 articleId, bool isActive) internal {
    return CallWrapper(self.toResourceId(), address(0)).setTipJarActive(articleId, isActive);
  }

  function addTipSplit(TipSystemType self, bytes32 articleId, address recipient, uint16 percentage) internal {
    return CallWrapper(self.toResourceId(), address(0)).addTipSplit(articleId, recipient, percentage);
  }

  function removeTipSplit(TipSystemType self, bytes32 articleId, address recipient) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeTipSplit(articleId, recipient);
  }

  function setTipSplitActive(TipSystemType self, bytes32 articleId, address recipient, bool isActive) internal {
    return CallWrapper(self.toResourceId(), address(0)).setTipSplitActive(articleId, recipient, isActive);
  }

  function getTotalTips(TipSystemType self, bytes32 articleId) internal view returns (uint256 __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getTotalTips(articleId);
  }

  function isTipJarActive(TipSystemType self, bytes32 articleId) internal view returns (bool __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).isTipJarActive(articleId);
  }

  function tipArticle(
    CallWrapper memory self,
    bytes32 articleId,
    address currency,
    uint256 amount,
    string memory message
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _tipArticle_bytes32_address_uint256_string.tipArticle,
      (articleId, currency, amount, message)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateTipJar(CallWrapper memory self, bytes32 articleId, address newRecipient) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_updateTipJar_bytes32_address.updateTipJar, (articleId, newRecipient));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setTipJarActive(CallWrapper memory self, bytes32 articleId, bool isActive) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_setTipJarActive_bytes32_bool.setTipJarActive, (articleId, isActive));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addTipSplit(CallWrapper memory self, bytes32 articleId, address recipient, uint16 percentage) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _addTipSplit_bytes32_address_uint16.addTipSplit,
      (articleId, recipient, percentage)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeTipSplit(CallWrapper memory self, bytes32 articleId, address recipient) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeTipSplit_bytes32_address.removeTipSplit, (articleId, recipient));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function setTipSplitActive(CallWrapper memory self, bytes32 articleId, address recipient, bool isActive) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _setTipSplitActive_bytes32_address_bool.setTipSplitActive,
      (articleId, recipient, isActive)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getTotalTips(CallWrapper memory self, bytes32 articleId) internal view returns (uint256 __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getTotalTips_bytes32.getTotalTips, (articleId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function isTipJarActive(CallWrapper memory self, bytes32 articleId) internal view returns (bool __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert TipSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_isTipJarActive_bytes32.isTipJarActive, (articleId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function tipArticle(
    RootCallWrapper memory self,
    bytes32 articleId,
    address currency,
    uint256 amount,
    string memory message
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _tipArticle_bytes32_address_uint256_string.tipArticle,
      (articleId, currency, amount, message)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateTipJar(RootCallWrapper memory self, bytes32 articleId, address newRecipient) internal {
    bytes memory systemCall = abi.encodeCall(_updateTipJar_bytes32_address.updateTipJar, (articleId, newRecipient));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setTipJarActive(RootCallWrapper memory self, bytes32 articleId, bool isActive) internal {
    bytes memory systemCall = abi.encodeCall(_setTipJarActive_bytes32_bool.setTipJarActive, (articleId, isActive));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function addTipSplit(RootCallWrapper memory self, bytes32 articleId, address recipient, uint16 percentage) internal {
    bytes memory systemCall = abi.encodeCall(
      _addTipSplit_bytes32_address_uint16.addTipSplit,
      (articleId, recipient, percentage)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeTipSplit(RootCallWrapper memory self, bytes32 articleId, address recipient) internal {
    bytes memory systemCall = abi.encodeCall(_removeTipSplit_bytes32_address.removeTipSplit, (articleId, recipient));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function setTipSplitActive(
    RootCallWrapper memory self,
    bytes32 articleId,
    address recipient,
    bool isActive
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _setTipSplitActive_bytes32_address_bool.setTipSplitActive,
      (articleId, recipient, isActive)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getTotalTips(RootCallWrapper memory self, bytes32 articleId) internal view returns (uint256 __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getTotalTips_bytes32.getTotalTips, (articleId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (uint256));
    }
  }

  function isTipJarActive(RootCallWrapper memory self, bytes32 articleId) internal view returns (bool __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_isTipJarActive_bytes32.isTipJarActive, (articleId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function callFrom(TipSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(TipSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(TipSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(TipSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(TipSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (TipSystemType) {
    return TipSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(TipSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _tipArticle_bytes32_address_uint256_string {
  function tipArticle(bytes32 articleId, address currency, uint256 amount, string memory message) external;
}

interface _updateTipJar_bytes32_address {
  function updateTipJar(bytes32 articleId, address newRecipient) external;
}

interface _setTipJarActive_bytes32_bool {
  function setTipJarActive(bytes32 articleId, bool isActive) external;
}

interface _addTipSplit_bytes32_address_uint16 {
  function addTipSplit(bytes32 articleId, address recipient, uint16 percentage) external;
}

interface _removeTipSplit_bytes32_address {
  function removeTipSplit(bytes32 articleId, address recipient) external;
}

interface _setTipSplitActive_bytes32_address_bool {
  function setTipSplitActive(bytes32 articleId, address recipient, bool isActive) external;
}

interface _getTotalTips_bytes32 {
  function getTotalTips(bytes32 articleId) external;
}

interface _isTipJarActive_bytes32 {
  function isTipJarActive(bytes32 articleId) external;
}

using TipSystemLib for TipSystemType global;
using TipSystemLib for CallWrapper global;
using TipSystemLib for RootCallWrapper global;
