// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { WaypointSystem } from "../../systems/WaypointSystem.sol";
import { WaypointGroupData } from "../../../dailydust/codegen/tables/WaypointGroup.sol";
import { WaypointStepData } from "../../../dailydust/codegen/tables/WaypointStep.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type WaypointSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cms", name: "WaypointSystem" }))
WaypointSystemType constant waypointSystem = WaypointSystemType.wrap(
  0x7379636d730000000000000000000000576179706f696e7453797374656d0000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title WaypointSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library WaypointSystemLib {
  error WaypointSystemLib_CallingFromRootSystem();

  function createWaypointGroup(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).createWaypointGroup(
        articleId,
        groupId,
        color,
        isPublic,
        name,
        description
      );
  }

  function updateWaypointGroup(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    return
      CallWrapper(self.toResourceId(), address(0)).updateWaypointGroup(
        articleId,
        groupId,
        color,
        isPublic,
        name,
        description
      );
  }

  function deleteWaypointGroup(WaypointSystemType self, bytes32 articleId, uint16 groupId) internal {
    return CallWrapper(self.toResourceId(), address(0)).deleteWaypointGroup(articleId, groupId);
  }

  function addWaypointStep(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).addWaypointStep(articleId, groupId, index, x, y, z, label);
  }

  function updateWaypointStep(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).updateWaypointStep(articleId, groupId, index, x, y, z, label);
  }

  function removeWaypointStep(WaypointSystemType self, bytes32 articleId, uint16 groupId, uint16 index) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeWaypointStep(articleId, groupId, index);
  }

  function moveWaypointStep(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).moveWaypointStep(articleId, groupId, fromIndex, toIndex);
  }

  function getWaypointGroup(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (WaypointGroupData memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getWaypointGroup(articleId, groupId);
  }

  function getWaypointStep(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (WaypointStepData memory __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).getWaypointStep(articleId, groupId, index);
  }

  function waypointGroupExists(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (bool __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).waypointGroupExists(articleId, groupId);
  }

  function waypointStepExists(
    WaypointSystemType self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (bool __auxRet0) {
    return CallWrapper(self.toResourceId(), address(0)).waypointStepExists(articleId, groupId, index);
  }

  function createWaypointGroup(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createWaypointGroup_bytes32_uint16_uint24_bool_string_string.createWaypointGroup,
      (articleId, groupId, color, isPublic, name, description)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateWaypointGroup(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateWaypointGroup_bytes32_uint16_uint24_bool_string_string.updateWaypointGroup,
      (articleId, groupId, color, isPublic, name, description)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function deleteWaypointGroup(CallWrapper memory self, bytes32 articleId, uint16 groupId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _deleteWaypointGroup_bytes32_uint16.deleteWaypointGroup,
      (articleId, groupId)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addWaypointStep(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _addWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string.addWaypointStep,
      (articleId, groupId, index, x, y, z, label)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function updateWaypointStep(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _updateWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string.updateWaypointStep,
      (articleId, groupId, index, x, y, z, label)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeWaypointStep(CallWrapper memory self, bytes32 articleId, uint16 groupId, uint16 index) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _removeWaypointStep_bytes32_uint16_uint16.removeWaypointStep,
      (articleId, groupId, index)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function moveWaypointStep(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _moveWaypointStep_bytes32_uint16_uint16_uint16.moveWaypointStep,
      (articleId, groupId, fromIndex, toIndex)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function getWaypointGroup(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (WaypointGroupData memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_getWaypointGroup_bytes32_uint16.getWaypointGroup, (articleId, groupId));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (WaypointGroupData));
    }
  }

  function getWaypointStep(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (WaypointStepData memory __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _getWaypointStep_bytes32_uint16_uint16.getWaypointStep,
      (articleId, groupId, index)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (WaypointStepData));
    }
  }

  function waypointGroupExists(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (bool __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _waypointGroupExists_bytes32_uint16.waypointGroupExists,
      (articleId, groupId)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function waypointStepExists(
    CallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (bool __auxRet0) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert WaypointSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _waypointStepExists_bytes32_uint16_uint16.waypointStepExists,
      (articleId, groupId, index)
    );
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function createWaypointGroup(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _createWaypointGroup_bytes32_uint16_uint24_bool_string_string.createWaypointGroup,
      (articleId, groupId, color, isPublic, name, description)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateWaypointGroup(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _updateWaypointGroup_bytes32_uint16_uint24_bool_string_string.updateWaypointGroup,
      (articleId, groupId, color, isPublic, name, description)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function deleteWaypointGroup(RootCallWrapper memory self, bytes32 articleId, uint16 groupId) internal {
    bytes memory systemCall = abi.encodeCall(
      _deleteWaypointGroup_bytes32_uint16.deleteWaypointGroup,
      (articleId, groupId)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function addWaypointStep(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _addWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string.addWaypointStep,
      (articleId, groupId, index, x, y, z, label)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function updateWaypointStep(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _updateWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string.updateWaypointStep,
      (articleId, groupId, index, x, y, z, label)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeWaypointStep(RootCallWrapper memory self, bytes32 articleId, uint16 groupId, uint16 index) internal {
    bytes memory systemCall = abi.encodeCall(
      _removeWaypointStep_bytes32_uint16_uint16.removeWaypointStep,
      (articleId, groupId, index)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function moveWaypointStep(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 fromIndex,
    uint16 toIndex
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _moveWaypointStep_bytes32_uint16_uint16_uint16.moveWaypointStep,
      (articleId, groupId, fromIndex, toIndex)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function getWaypointGroup(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (WaypointGroupData memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(_getWaypointGroup_bytes32_uint16.getWaypointGroup, (articleId, groupId));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (WaypointGroupData));
    }
  }

  function getWaypointStep(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (WaypointStepData memory __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _getWaypointStep_bytes32_uint16_uint16.getWaypointStep,
      (articleId, groupId, index)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (WaypointStepData));
    }
  }

  function waypointGroupExists(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId
  ) internal view returns (bool __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _waypointGroupExists_bytes32_uint16.waypointGroupExists,
      (articleId, groupId)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function waypointStepExists(
    RootCallWrapper memory self,
    bytes32 articleId,
    uint16 groupId,
    uint16 index
  ) internal view returns (bool __auxRet0) {
    bytes memory systemCall = abi.encodeCall(
      _waypointStepExists_bytes32_uint16_uint16.waypointStepExists,
      (articleId, groupId, index)
    );

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    // skip decoding an empty result, which can happen after expectRevert
    if (result.length != 0) {
      return abi.decode(result, (bool));
    }
  }

  function callFrom(WaypointSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(WaypointSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(WaypointSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(WaypointSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(WaypointSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (WaypointSystemType) {
    return WaypointSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(WaypointSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createWaypointGroup_bytes32_uint16_uint24_bool_string_string {
  function createWaypointGroup(
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) external;
}

interface _updateWaypointGroup_bytes32_uint16_uint24_bool_string_string {
  function updateWaypointGroup(
    bytes32 articleId,
    uint16 groupId,
    uint24 color,
    bool isPublic,
    string memory name,
    string memory description
  ) external;
}

interface _deleteWaypointGroup_bytes32_uint16 {
  function deleteWaypointGroup(bytes32 articleId, uint16 groupId) external;
}

interface _addWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string {
  function addWaypointStep(
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) external;
}

interface _updateWaypointStep_bytes32_uint16_uint16_int32_int32_int32_string {
  function updateWaypointStep(
    bytes32 articleId,
    uint16 groupId,
    uint16 index,
    int32 x,
    int32 y,
    int32 z,
    string memory label
  ) external;
}

interface _removeWaypointStep_bytes32_uint16_uint16 {
  function removeWaypointStep(bytes32 articleId, uint16 groupId, uint16 index) external;
}

interface _moveWaypointStep_bytes32_uint16_uint16_uint16 {
  function moveWaypointStep(bytes32 articleId, uint16 groupId, uint16 fromIndex, uint16 toIndex) external;
}

interface _getWaypointGroup_bytes32_uint16 {
  function getWaypointGroup(bytes32 articleId, uint16 groupId) external;
}

interface _getWaypointStep_bytes32_uint16_uint16 {
  function getWaypointStep(bytes32 articleId, uint16 groupId, uint16 index) external;
}

interface _waypointGroupExists_bytes32_uint16 {
  function waypointGroupExists(bytes32 articleId, uint16 groupId) external;
}

interface _waypointStepExists_bytes32_uint16_uint16 {
  function waypointStepExists(bytes32 articleId, uint16 groupId, uint16 index) external;
}

using WaypointSystemLib for WaypointSystemType global;
using WaypointSystemLib for CallWrapper global;
using WaypointSystemLib for RootCallWrapper global;
