// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { HookContext } from "@dust/world/src/ProgramHooks.sol";

/**
 * @title IBaseProgram
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBaseProgram {
  function rg_dd_ab564f__onAttachProgram(HookContext calldata ctx) external;

  function rg_dd_ab564f__onDetachProgram(HookContext calldata ctx) external;

  function rg_dd_ab564f___msgSender() external view returns (address);

  function rg_dd_ab564f___msgValue() external view returns (uint256);
}
